server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # ОСЬ ЦЕЙ РЯДОК РОБИТЬ МАГІЮ!
        # Він каже: шукай файл ($uri), якщо немає - шукай папку ($uri/),
        # якщо немає - віддавай /index.html
        try_files $uri $uri/ /index.html;
    }

    # Логування (необов'язково, але корисно для дебагу)
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}