services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: synergy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Додаємо перевірку: чи готова база приймати запити?
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d synergy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        # Бекенд чекатиме, поки healthcheck бази не стане "healthy"
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/synergy_db

volumes:
  postgres_data: